In [1]:
import pandas as pd

In [2]:
prefix ='https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow'
url=f'{prefix}/yellow_tripdata_2021-01.csv.gz'

In [6]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates
)

In [4]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [7]:
len(df)

1369765

In [13]:
!uv add sqlalchemy

Resolved 117 packages in 2.50s
Prepared 2 packages in 105ms
░░░░░░░░░░░░░░░░░░░░ [0/2] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 2 packages in 33ms
 + greenlet==3.3.1
 + sqlalchemy==2.0.46

In [15]:
!uv add psycopg2-binary

Resolved 118 packages in 237ms
Prepared 1 package in 56ms
░░░░░░░░░░░░░░░░░░░░ [0/1] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 1 package in 11ms.11
 + psycopg2-binary==2.9.11

In [9]:
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg://root:root@localhost:5432/ny_taxi')

In [11]:
df.head(0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [10]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [12]:
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000,
)

In [13]:
df_iter

In [14]:
!uv add tqdm

Resolved 119 packages in 48ms
Audited 10 packages in 87ms

In [15]:
from tqdm.auto import tqdm

In [16]:
for df_chunk in tqdm(df_iter) :
  df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

0it [00:00, ?it/s]

In [28]:
df= next(df_iter)

In [29]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
300000,2,2021-01-08 21:57:23,2021-01-08 21:57:32,1,0.01,5,N,255,255,1,30.0,0.0,0.0,4.00,0.00,0.3,34.30,0.0
300001,2,2021-01-08 21:28:00,2021-01-08 21:46:38,1,11.74,1,N,194,95,1,32.0,0.5,0.5,7.88,6.12,0.3,47.30,0.0
300002,2,2021-01-08 21:29:09,2021-01-08 21:36:33,3,1.75,1,N,142,141,2,8.0,0.5,0.5,0.00,0.00,0.3,11.80,2.5
300003,2,2021-01-08 21:46:10,2021-01-08 22:07:13,2,8.67,1,N,262,18,1,26.5,0.5,0.5,7.58,0.00,0.3,37.88,2.5
300004,1,2021-01-08 21:16:46,2021-01-08 21:20:29,1,0.90,1,N,168,69,2,5.5,0.5,0.5,0.00,0.00,0.3,6.80,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399995,2,2021-01-11 17:03:58,2021-01-11 17:08:23,1,1.08,1,N,162,107,1,5.5,1.0,0.5,1.00,0.00,0.3,10.80,2.5
399996,1,2021-01-11 17:09:26,2021-01-11 17:31:25,1,4.70,1,N,239,234,1,18.5,3.5,0.5,4.55,0.00,0.3,27.35,2.5
399997,1,2021-01-11 17:46:24,2021-01-11 17:54:11,1,1.10,1,N,161,233,2,7.0,3.5,0.5,0.00,0.00,0.3,11.30,2.5
399998,2,2021-01-11 17:31:45,2021-01-11 17:48:09,1,3.16,1,N,161,45,1,13.0,1.0,0.5,3.46,0.00,0.3,20.76,2.5
399999,2,2021-01-11 17:51:49,2021-01-11 17:59:38,1,1.55,1,N,144,4,2,7.5,1.0,0.5,0.00,0.00,0.3,11.80,2.5